# Gradle performance settings
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Parchment mappings
parchment_minecraft_version=1.21.7
parchment_mappings_version=2025.07.18

# Minecraft and NeoForge versions
minecraft_version=1.21.7
minecraft_version_range=[1.21.7,1.22)
neo_version=21.7.25-beta
loader_version_range=[1,)

# Mod metadata
mod_id=tremendousstorage
mod_name=TremendousStorage
mod_license=MIT
mod_version=1.0.0
mod_group_id=net.bobofraggins.tremendousstorage

# Optional dependency versions
structure_pool_api_version=1.2.1+1.21.1-neoforge
emi_version=1.1.22+1.21.1+neoforge
rei_version=16.0.799
